import java.math.BigInteger;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.Scanner;


class SHA {
    public static byte[] getSHA(String input) throws NoSuchAlgorithmException {
  
        MessageDigest md = MessageDigest.getInstance("SHA-256");
       
        return md.digest(input.getBytes(StandardCharsets.UTF_8));
    }

    public static String toHexString(byte[] hash) {
   
        BigInteger number = new BigInteger(1, hash);
      
        String hexString = number.toString(16);

  
        while (hexString.length() < 64) {
            hexString = "0" + hexString;
        }

        return hexString;
    }


    public static void main(String[] args) {
        try {
            System.out.println("HashCode Generated by SHA-256 for:\n");
            Scanner scanner=new Scanner(System.in);
            System.out.println("Enter the 1 string");
            String s1 = scanner.nextLine();
            System.out.println(s1 + " : " + toHexString(getSHA(s1)));

            System.out.println("Enter the 2 string");
            String s2 =scanner.nextLine();

            System.out.println(s2 + " : " + toHexString(getSHA(s2)));
            System.out.println("Enter the 3 string");
            String s3 = scanner.nextLine();
            System.out.println(s3 + " : " + toHexString(getSHA(s3)));
        } catch (NoSuchAlgorithmException e) {
            System.out.println("Exception thrown for incorrect algorithm: " + e);
        }
    }
}
